[[apps]]
title = "KDE Development Desktop"
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/kde-dev/assets/icon.png"

[apps.runner]
type = "docker"
name = "WolfKDEDev"
image = "ghcr.io/devilblader87/gow/kde-dev:enhanced"
env = [
    "GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*",
    "KDE_FULL_SESSION=true",
    "DESKTOP_SESSION=plasma"
]
mounts = [
    "/mnt/Wolf:/mnt/Wolf:rw",
    "kde-dev-home:/home/retro:rw",
    "kde-dev-config:/home/retro/.config:rw"
]
base_create_json = """{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": true,
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}"""
