[[apps]]
title = "Enhanced XFCE Desktop"
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/xfce/assets/icon.png"

[apps.runner]
type = "docker"
name = "WolfXFCEEnhanced"
image = "ghcr.io/games-on-whales/xfce:enhanced"
env = [
    "RUN_SWAY=true",
    "GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*",
]
devices = []
mounts = [
    "xfce-enhanced-home:/home/retro:rw",
    "xfce-projects:/mnt/Wolf/Projects:rw",
    "xfce-unity:/mnt/Wolf/Unity:rw",
    "xfce-downloads:/mnt/Wolf/Downloads:rw",
    "xfce-documents:/mnt/Wolf/Documents:rw"
]
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "Ulimits": [{"Name":"nofile", "Hard":10240, "Soft":10240}],
    "Privileged": false,
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
"""