baseURL = 'https://games-on-whales.github.io/wildlife/'
title = 'Wildlife'
languageCode = 'en-us'

theme = ["hugo-book"]

[params]
BookSearch = false
BookTheme = 'light'
BookSection = "*"
BookRepo = "https://github.com/games-on-whales/wildlife"

[module]
[[module.mounts]]
source = '../apps/'
target = 'content/apps'
excludeFiles = ['build/**', 'build'] # TODO: doesn't work

[[module.mounts]]
source = "content"
target = "content"

# See: https://stackoverflow.com/a/63206852
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
