[[apps]]
title = 'VR Streaming (ALVR + SteamVR)'
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/vr-steamvr/assets/icon.png"

[apps.runner]
type = 'docker'
name = 'WolfVRStreaming'
image = 'ghcr.io/games-on-whales/vr-steamvr:edge'
env = [
    'GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*',
    'ALVR_SERVER_HOST=0.0.0.0',
    'ALVR_WEB_PORT=8082',
    'STEAM_VR=1',
    'RUN_SWAY=true'
]
devices = []
mounts = [
    '/tmp/.X11-unix:/tmp/.X11-unix:rw',
    'alvr-data:/home/retro/.local/share/alvr:rw',
    'steamvr-data:/home/retro/.steam:rw'
]
ports = [
    '8082:8082/tcp',  # ALVR Web Interface
    '9943:9943/udp',  # ALVR Streaming Port 1
    '9944:9944/udp'   # ALVR Streaming Port 2
]
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": true,
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  },
  "User": "0:0"
}
\
"""
