name: 🚀 Quick Build

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'What to build'
        type: choice
        required: true
        default: 'xfce-only'
        options:
          - 'xfce-only'
          - 'all-apps'
          - 'base-and-xfce'
      image_tag:
        description: 'Image tag'
        type: string
        default: 'latest'
      push_to_registry:
        description: 'Push to registry'
        type: boolean
        default: true

jobs:
  quick-xfce:
    if: contains(fromJson('["xfce-only", "base-and-xfce"]'), inputs.build_target)
    uses: ./.github/workflows/build-enhanced-xfce.yml
    with:
      push_to_registry: ${{ inputs.push_to_registry }}
      image_tag: ${{ inputs.image_tag }}
      use_existing_base: ${{ inputs.build_target != 'base-and-xfce' }}
      base_app_image: 'ghcr.io/games-on-whales/base-app:edge'
    secrets: inherit

  all-images:
    if: inputs.build_target == 'all-apps'
    uses: ./.github/workflows/build-all-images.yml
    with:
      push_to_registry: ${{ inputs.push_to_registry }}
      image_tag: ${{ inputs.image_tag }}
      build_base_images: false
    secrets: inherit

  base-and-xfce:
    if: inputs.build_target == 'base-and-xfce'
    uses: ./.github/workflows/build-all-images.yml
    with:
      push_to_registry: ${{ inputs.push_to_registry }}
      image_tag: ${{ inputs.image_tag }}
      build_base_images: true
    secrets: inherit
